apiVersion: v1
kind: Service
metadata:
  name: {{ template "nginx.fullname" . }}
  labels:
    app: {{ template "nginx.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{- with .Values.nginx.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.nginx.service.type }}
  {{- if (or (eq .Values.nginx.service.type "LoadBalancer") (eq .Values.nginx.service.type "NodePort")) }}
  externalTrafficPolicy: {{ .Values.nginx.service.externalTrafficPolicy | quote }}
  {{- end }}
  {{- if (and (eq .Values.nginx.service.type "LoadBalancer") (not (empty .Values.nginx.service.loadBalancerIP))) }}
  loadBalancerIP: {{ .Values.nginx.service.loadBalancerIP }}
  {{- end }}
  ports:
    - name: http
      port: {{ .Values.nginx.service.port }}
      targetPort: 80
      {{- if (and (eq .Values.nginx.service.type "NodePort") (not (empty .Values.nginx.service.nodePorts.http)))}}
      nodePort: {{ .Values.nginx.service.nodePorts.http }}
      {{- end }}
    - name: relay-tcp
      port: {{ .Values.relay_port }}
      targetPort: {{ .Values.relay_port }}
      {{- if (and (eq .Values.nginx.service.type "NodePort") (not (empty .Values.nginx.service.nodePorts.relay)))}}
      nodePort: {{ .Values.nginx.service.nodePorts.relay }}
      {{- end }}
{{- if .Values.influxdb.config.udp.enabled }}
    - name: relay-udp
      port: {{ .Values.nginx.nginxConfig.stream.udp_listen }}
      targetPort: {{ .Values.nginx.nginxConfig.stream.udp_listen }}
      protocol: UDP
      {{- if (and (eq .Values.nginx.service.type "NodePort") (not (empty .Values.nginx.service.nodePorts.relay)))}}
      nodePort: {{ .Values.nginx.service.nodePorts.relay }}
      {{- end }}
{{ end }}
  selector:
    app: {{ template "nginx.fullname" . }}